@baseUrl = http://127.0.0.1:3500
@accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2YTJkNmJkZGMwZWM2MzVkOTUyMDkwMjYiLCJ1c2VybmFtZSI6InVzZXJlZG9zIiwiaXNBY3RpdmUiOnRydWUsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3ODEzNjMyNTAsImV4cCI6MTc4MTM2Njg1MH0.e8ji5A_DFwE1uBXkFPavy01XjDHw2EyzfDl2o2FPLIg

### Ana sayfa public 
# @name home

GET {{baseUrl}}


### Register

# @name register

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "adminedos",
  "email": "adminedos@mail.com",
  "password": "Adminedos4321!",
  "isAdmin" : true,
  "isActive":true
  
}
### login
# @name userlogin


post {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "useredos",
    "password": "Useredos4321!"
}

###
# @name logout
get {{baseUrl}}/auth/logout
Authorization: {{accessToken}}





###
# @name getProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{accessToken}}

###
# @name senaryo 2 token yok
GET {{baseUrl}}/users/profile

###  SENARYO 3: Geçersiz token
GET {{baseUrl}}/users/profile
Authorization: Bearer invalid.token.123



### admin listeler normal kullanıcı lısteleyemez

# @name list
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

###
# @name guncelle

PUT {{baseUrl}}/users/6a2c711a15d3bdf5b25144f0
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "password": "adminelif123456!"
}


### _____________________car controller testing____

# @name carcreate via admin
POST {{baseUrl}}/cars
Authorization: Bearer {{accessToken}}
Content-Type: application/json

#{
  #"brand": "BMW",
  #"model": "X5",
  #"year": 1800,
  #"plateNumber": "ABC123",
  #"isAutomatic": true,
  #"pricePerDay": 150,
  #"isPublish": true
#}
#
  #"brand": "Audi",
  #"model": "A4",
  #"year": 2024,
  #"plateNumber": "AUD003",
  #"isAutomatic": false,
  #"pricePerDay": 120,
  #"isPublish": false
#

{
  "brand": "Audi",
  "model": "A4",
  "year": 2024,
  "plateNumber": "AUD002",
  "isAutomatic": false,
  "pricePerDay": 120,
  "isPublish": false
}
###



### (Araçları listele)


# @name getCars
GET {{baseUrl}}/cars
Authorization: Bearer {{accessToken}}

###filter ile 
# @nameurl e ekle sorguyu
GET {{baseUrl}}/cars/?filter[isPublish]=true
Authorization: Bearer {{accessToken}}


###
#GET {{baseUrl}}/cars?search[brand]=BMW
#Authorization: Bearer {{{{accessToken}}}}



### SORT: Fiyata göre (yüksekten düşüğe)
#GET {{baseUrl}}/cars?sort[pricePerDay]=-1
#Authorization: Bearer {{{{accessToken}}}}

### PAGINATION: 2. sayfa, 5 araç
#GET {{baseUrl}}/cars?page=2&limit=5
##Authorization: Bearer {{{{accessToken}}}}

### Filter + Search + Sort
#GET {{baseUrl}}/cars?filter[isPublish]=true&search[brand]=BMW&sort[pricePerDay]=-1
#Authorization: Bearer {{{{accessToken}}}}