@baseUrl = http://127.0.0.1:8000

###
GET {{baseUrl}}/personels?filter[userName]=elif

###
# @name login

post {{baseUrl}}/auth/login
Content-Type: application/json

{
    "userName": "elif",
    "password": "1234"
}
###
GET http://127.0.0.1:8000/departments
###


# @name logout
post {{baseUrl}}/auth/logout
Authorization: Token 059ce32e6f6737a3a7c45a67f09e772e44db7c2f34c3707f1bac37746145d961



###?TOKEN ALMA###


# @name tokenCreate
post {{baseUrl}}/tokens
Content-Type: application/json

{
    "userId": "6a039d0f9e50dec6416a9a35"
  
}

###

# @name tokenList
get {{baseUrl}}/tokens


###

# @name tokenRead
get {{baseUrl}}/tokens/6a03c43a398642975b8e4032


###

# @name tokenUpdate
put {{baseUrl}}/tokens/6a03c43a398642975b8e4032
Content-Type: application/json

{
    "name": "personnel abc"
}


###

# @name tokenDelete
delete {{baseUrl}}/tokens/6a03c43a398642975b8e4032
###


GET {{baseUrl}}/personels
Authorization: Token a5d6bca2a9b4476ba7dae323d6c276d1d91437fa58b4c4d652c2a73623b88bfb



###

# @ name tokenolmadan 
GET {{baseUrl}}/personels