@baseUrl = http://127.0.0.1:8000

###

# @name departmentlisteleme
get {{baseUrl}}/departments

###

# @name departmentRead
get {{baseUrl}}/departments/6a01a04040a52a22da417b78


###

# @name departmentCreate
post {{baseUrl}}/departments
Content-Type: application/json

{
    "name": "department software"
}

###

# @name departmentUpdate
put {{baseUrl}}/departments/6a01d2fa06a9fe7af549d257
Authorization:Token c2febef74d0e68eb67cbfa7c1d057d2efe9df84261178270aaa51f0d6afbfe11
Content-Type: application/json

{
    "name": "lead is updating own department.."
}
###
# @name departmentDelete
delete {{baseUrl}}/departments/6a038839d2b39772287ec25e

###