@baseUrl = http://127.0.0.1:8000

###


# @name personnelList
get {{baseUrl}}/personels

###

# @name personnelCreate
post {{baseUrl}}/personels
Content-Type: application/json

{
  "userName": "Elif123",
  "firstName": "elif123",
  "lastName": "User123",
  "departmentId": "6a038da634cd87ba1864ef77",
  "title": "System Admin12",
  "email": "adminelif123@test.com",
  "password": "1234",
  "description": "This is admin user12",
  "phone": "+9015551112233",
  "salary": {
    "amount": 500100,
    "currency": "TRY"
  },
  "role": "admin",
  "permissions": {
    "canEdit": true,
    "canDelete": true,
    "canCreate": true,
    "canView": true
  },
  "isActive": true,
  "startedAt": "2026-05-12T00:00:00.000Z"
}

# {
#     "firstName": "adminF",
#     "lastName": "adminL",
#     "userame": "admin",
#     "departmentId":"6a01a04040a52a22da417b78",
#     "title":"admin",
#     "email": "admin@test.com",
#     "password": "1234",
#     "description": "this is admin",
#     "isAdmin": true,
#     "phone": "01234567890"
# }



###

# @name personnelRead
get {{baseUrl}}/personels?userName=elif
###

# @name personnelUpdate
put {{baseUrl}}/personels/6a039ffa3c1a4314d1640bc2
Content-Type: application/json
Authorization: Token a5d6bca2a9b4476ba7dae323d6c276d1d91437fa58b4c4d652c2a73623b88bfb

{
    "role": "lead"
}


###

# @name personnelDelete
delete {{baseUrl}}/personels/6a03a3b347fdab14347de022


###
# @name personnelCreate
post {{baseUrl}}/personels
Content-Type: application/json

{
  "userName": "leadUser03",
  "firstName": "Lead03",
  "lastName": "Manager03",
  "departmentId": "6a01d2fa06a9fe7af549d257",
  "title": "Team Lead03",
  "email": "lead03@test.com",
  "password": "1234",
  "description": "Lead user for testing",
  "phone": "+901111111112",
  "salary": {
    "amount": 7040,
    "currency": "TRY"
  },
  "role": "lead",
  "permissions": {
    "canEdit": true,
    "canDelete": false,
    "canCreate": true,
    "canView": true
  },
  "isActive": true,
  "startedAt": "2026-05-12T00:00:00.000Z"
}