@baseUrl = http://127.0.0.1:8000

###


# @name personnelList
get {{baseUrl}}/personels

###

# @name personnelCreate
post {{baseUrl}}/personels
Content-Type: application/json

{
  "userName": "Elif123",
  "firstName": "elif123",
  "lastName": "User123",
  "departmentId": "6a038da634cd87ba1864ef77",
  "title": "System Admin12",
  "email": "adminelif123@test.com",
  "password": "1234",
  "description": "This is admin user12",
  "phone": "+9015551112233",
  "salary": {
    "amount": 500100,
    "currency": "TRY"
  },
  "role": "admin",
  "permissions": {
    "canEdit": true,
    "canDelete": true,
    "canCreate": true,
    "canView": true
  },
  "isActive": true,
  "startedAt": "2026-05-12T00:00:00.000Z"
}

# {
#     "firstName": "adminF",
#     "lastName": "adminL",
#     "userame": "admin",
#     "departmentId":"6a01a04040a52a22da417b78",
#     "title":"admin",
#     "email": "admin@test.com",
#     "password": "1234",
#     "description": "this is admin",
#     "isAdmin": true,
#     "phone": "01234567890"
# }



###

# @name personnelRead
get {{baseUrl}}/personels?userName=elif
###

# @name personnelUpdate
put {{baseUrl}}/personels/6a0628958f2be64ff4d47958
Content-Type: application/json
Authorization: Token 9ed5b344fa8dde6302fabc3aae30f3490a7e83e816d865aaf89c59dec125996e

{
    "password": "1234"
}


###

# @name personnelDelete
delete {{baseUrl}}/personels/6a03a38ca49f07ec5f7167a8
Authorization: Token 059ce32e6f6737a3a7c45a67f09e772e44db7c2f34c3707f1bac37746145d961


###
# @name personnelCreate
post {{baseUrl}}/personels
Content-Type: application/json

{
  "userName": "leadUser03",
  "firstName": "Lead03",
  "lastName": "Manager03",
  "departmentId": "6a01d2fa06a9fe7af549d257",
  "title": "Team Lead03",
  "email": "lead03@test.com",
  "password": "1234",
  "description": "Lead user for testing",
  "phone": "+901111111112",
  "salary": {
    "amount": 7040,
    "currency": "TRY"
  },
  "role": "lead",
  "permissions": {
    "canEdit": true,
    "canDelete": false,
    "canCreate": true,
    "canView": true
  },
  "isActive": true,
  "startedAt": "2026-05-12T00:00:00.000Z"
}